travis:
  secure:
    BINSTAR_TOKEN: BvJ1GCI5o8avLk7LRwIUfnVc9HN18qjxQJCjyT8Tvc1m2ZOWbsDO+9pR1A4QrmkQgnVICWnNQskwK+PmqB2I1GT8FYpQ/DNgSGZSAjcrdh9PqJIqUjYfI5pIiz9wN5NofUINtFXGigtiy5Cz3zPmTrMEJGu7X7zJ6zCRfG6aKVAON90aq/2oKo1um68dIeYWc377sqck+5zO5agd1Jrs8MFujfvk0otJw0kY/+Ywp4S2UbwIW21CpyeMkW/FQPzn9xaP9OGunZHKd16/edKz5wnKlfL8v2JOFsDUVhzhgZ0CKHe1QtyvbGixiKztAASqZ6sFg5t/dhhskx3C66us/NKjc9qFBfs1ONYOU/7wdBoY/YLg9Xv15fqEKQ7tGZDFgNOG2ugzAEXUfvqg3MJFnthM0WhOsmtKCC8yqlQdP8FY1G4uhaF62Xz31yfLDXicHCjSY3iyRNDiwaq6bgJVR7HT6VD98tW1Hrhu7FhhAXTsRX+uDjLz2Wzh2Olyg3k81z8PtS+RG6W16nzTH/uGEy3KvB0/emHlP2gURIemQzNWtKPbYrMvB+F7XDyGhTPkR25+xReU65SLyd8fA1Rcz2eItiO4i80o67/hiV0aQ6AhTu6hn6+w2Im7tbMFtaT53jdnijTfHq8/4u5ZAIvgtmwjHOgr9dh1nZagb9MpEFk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
